#!/usr/bin/env python

class Solution(object):
    def isValid(self, s):
        """
        :type s: str
        :rtype: bool
        """
        if len(s)%2 != 0:
            return False
        
        d = {'(':')','[':']','{':'}'}
        
        stk = []
        
        for x in s:
            if x in d.keys():
                stk.append(d[x])
            elif x in stk:
                stk.pop()
            else:
                stk.append(x)
        
        if len(stk)==0:
            return True
        
        return False

if __name__ == "__main__":
    print(Solution().isValid(""))
